galaxyproject/gxy.io

group_vars/all.yaml
Works from my fork, so fingers crossed.
=> Production deploy test

group_vars/all.yaml
Fingers crossed it works end to end finally.
=> Deployment test

group_vars/all.yaml
=> Add routes for smorg slack

README.md, group_vars/all.yaml, templates/lambda_function.py.j2, tests/test_function.py
I am absolutely not sure this works, do we have a staging environment?
=> Allow captures and replacements

group_vars/all.yaml
I think i've maybe got the GTN side done
=> Add alternative prefix for gtn

group_vars/all.yaml
guess we hit another 400 joins during the week..
=> Update smorg invite link again

group_vars/all.yaml
Added links for PDAL-seq paper.
=> Added a Publication section in all.yml for publications that have links to Galaxy. 

group_vars/all.yaml
Add /p/2024-nar for 2024 NAR Community paper
=> 2024 NAR redirect

group_vars/all.yaml
... well ... link to wbf slides
=> Link to wbf slides

group_vars/all.yaml
Short URL to be used on online to promote the open call for trainers to  the Galaxy Training Academy
=> added link to the news post about the open call for trainers to GTA

group_vars/all.yaml
https://www.eebgschool.org/schedule
=> Link to EEBG24

group_vars/all.yaml
=> Update single cell welcome url

group_vars/all.yaml
Added a GTA event page short link which can be used for the banner.
=> added GTA event page short link

group_vars/all.yaml
=> Update singlecell.usegalaxy.org welcome

group_vars/all.yaml
=> update GTN slack invite

group_vars/all.yaml
New short link to conference slides for: American Society for Microbiology, Next-Generation Sequencing 2024
=> New short link to Oct 15 conference slides

group_vars/all.yaml
gxy.io short link for GTN-Ludwig MNIST tutorial
=> Ludwig-mnist-tutorial

group_vars/all.yaml
=> Update all.yaml for the GTN invite link

group_vars/all.yaml
=> add ncat-25 slides redirect

group_vars/all.yaml
=> create gbcc25 redirect

group_vars/all.yaml
GTN Slack invitation link update
@shiltemann
=> Update all.yaml GTN Slack invitation link update

group_vars/all.yaml
Will change this link as soon as we have a proper DOI
=> add link to a sustainability report
